# Generated by Django 2.2.5 on 2020-03-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20200307_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('cancel', 'Cancel')], default='pending', max_length=12),
        ),
    ]
