# Generated by Django 2.2.5 on 2020-03-14 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200106_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='accuracy',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, message='0 <= 점수 <= 10'), django.core.validators.MinValueValidator(0, message='0 <= 점수 <= 10')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='check_in',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, message='0 <= 점수 <= 10'), django.core.validators.MinValueValidator(0, message='0 <= 점수 <= 10')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='cleanliness',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, message='0 <= 점수 <= 10'), django.core.validators.MinValueValidator(0, message='0 <= 점수 <= 10')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, message='0 <= 점수 <= 10'), django.core.validators.MinValueValidator(0, message='0 <= 점수 <= 10')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, message='0 <= 점수 <= 10'), django.core.validators.MinValueValidator(0, message='0 <= 점수 <= 10')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, message='0 <= 점수 <= 10'), django.core.validators.MinValueValidator(0, message='0 <= 점수 <= 10')]),
        ),
    ]
